dist: trusty
sudo: required
services:
- docker
language: python
python:
- '2.7'
install:
- pip install requests mockito
script:
- "./script.sh"
- export WEBSERVER_TEST_PAGES_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'
  webserver_test_pages)
- echo $WEBSERVER_TEST_PAGES_IP
- python -m unittest discover app
- sonar-scanner
before_install:
- openssl aes-256-cbc -K $encrypted_046cc4d61ee9_key -iv $encrypted_046cc4d61ee9_iv
  -in archive.tar.enc -out archive.tar -d
- tar xvf archive.tar
addons:
  sonarqube:
    token:
      secure: 5c495226de78494f99b3717bff5ec18a0a52dd1c